// Cyclone Scenarios Presets for instant testing
window.CYCLONE_PRESETS = {
    "amphan_super_cyclone": {
        "name": "Super Cyclone (Amphan-like Profile)",
        "desc": "Category 5 equivalent over Central Bay of Bengal with explosive rapid intensification potential",
        "data": {
            "latitude": 16.2,
            "longitude": 86.8,
            "season": 2024,
            "forecast_horizon_h": 24,
            "storm_speed_kts": 14.0,
            "storm_direction_deg": 340.0,
            "movement_distance_from_previous_km": 78.0,
            "wind_change_from_previous_kts": 15.0,
            "pressure_change_from_previous_hpa": -12.0,
            "wmo_wind_kts": 125.0,
            "wmo_pressure_hpa": 925.0,
            "imd_newdelhi_wind_kts": 125.0,
            "imd_newdelhi_pressure_hpa": 925.0,
            "usa_wind_kts": 130.0,
            "usa_pressure_hpa": 920.0,
            "weather_elevation_m": 0.0,
            "temperature_2m_c": 31.2,
            "relative_humidity_pct": 89.0,
            "dew_point_2m_c": 28.4,
            "surface_pressure_hpa": 995.0,
            "wind_speed_10m_kmh": 110.0,
            "wind_direction_10m_deg": 140.0,
            "wind_gusts_10m_kmh": 165.0,
            "precipitation_1h_mm": 35.0,
            "precipitation_24h_mm": 240.0,
            "precipitation_72h_mm": 410.0,
            "precipitation_168h_mm": 550.0,
            "soil_moisture_0_7cm_m3m3": 0.38,
            "landfall_indicator": 0,
            "distance_to_land_source": 320.0
        }
    },
    "fani_extremely_severe": {
        "name": "Extremely Severe Cyclonic Storm (Fani-like)",
        "desc": "Approaching Odisha / Northern Andhra coast with very high sustained winds and heavy surges",
        "data": {
            "latitude": 18.5,
            "longitude": 85.5,
            "season": 2024,
            "forecast_horizon_h": 12,
            "storm_speed_kts": 11.0,
            "storm_direction_deg": 30.0,
            "movement_distance_from_previous_km": 60.0,
            "wind_change_from_previous_kts": 8.0,
            "pressure_change_from_previous_hpa": -6.0,
            "wmo_wind_kts": 105.0,
            "wmo_pressure_hpa": 940.0,
            "imd_newdelhi_wind_kts": 105.0,
            "imd_newdelhi_pressure_hpa": 940.0,
            "usa_wind_kts": 110.0,
            "usa_pressure_hpa": 938.0,
            "weather_elevation_m": 0.0,
            "temperature_2m_c": 30.0,
            "relative_humidity_pct": 86.0,
            "dew_point_2m_c": 27.2,
            "surface_pressure_hpa": 998.0,
            "wind_speed_10m_kmh": 85.0,
            "wind_direction_10m_deg": 110.0,
            "wind_gusts_10m_kmh": 130.0,
            "precipitation_1h_mm": 28.0,
            "precipitation_24h_mm": 190.0,
            "precipitation_72h_mm": 320.0,
            "precipitation_168h_mm": 420.0,
            "soil_moisture_0_7cm_m3m3": 0.35,
            "landfall_indicator": 0,
            "distance_to_land_source": 110.0
        }
    },
    "cyclonic_storm_tamilnadu": {
        "name": "Cyclonic Storm (Southwest Bay of Bengal)",
        "desc": "Moderate Cyclonic Storm moving towards Tamil Nadu / Puducherry coast",
        "data": {
            "latitude": 11.8,
            "longitude": 82.5,
            "season": 2024,
            "forecast_horizon_h": 24,
            "storm_speed_kts": 9.0,
            "storm_direction_deg": 290.0,
            "movement_distance_from_previous_km": 48.0,
            "wind_change_from_previous_kts": 4.0,
            "pressure_change_from_previous_hpa": -3.0,
            "wmo_wind_kts": 50.0,
            "wmo_pressure_hpa": 992.0,
            "imd_newdelhi_wind_kts": 50.0,
            "imd_newdelhi_pressure_hpa": 992.0,
            "usa_wind_kts": 50.0,
            "usa_pressure_hpa": 992.0,
            "weather_elevation_m": 0.0,
            "temperature_2m_c": 29.5,
            "relative_humidity_pct": 82.0,
            "dew_point_2m_c": 25.8,
            "surface_pressure_hpa": 1005.0,
            "wind_speed_10m_kmh": 50.0,
            "wind_direction_10m_deg": 80.0,
            "wind_gusts_10m_kmh": 70.0,
            "precipitation_1h_mm": 15.0,
            "precipitation_24h_mm": 95.0,
            "precipitation_72h_mm": 160.0,
            "precipitation_168h_mm": 220.0,
            "soil_moisture_0_7cm_m3m3": 0.30,
            "landfall_indicator": 0,
            "distance_to_land_source": 190.0
        }
    },
    "tropical_depression_monsoon": {
        "name": "Deep Depression (North Bay of Bengal)",
        "desc": "Monsoon depression forming over head Bay of Bengal near West Bengal / Bangladesh border",
        "data": {
            "latitude": 20.8,
            "longitude": 89.2,
            "season": 2024,
            "forecast_horizon_h": 18,
            "storm_speed_kts": 12.0,
            "storm_direction_deg": 320.0,
            "movement_distance_from_previous_km": 55.0,
            "wind_change_from_previous_kts": 2.0,
            "pressure_change_from_previous_hpa": -2.0,
            "wmo_wind_kts": 32.0,
            "wmo_pressure_hpa": 998.0,
            "imd_newdelhi_wind_kts": 32.0,
            "imd_newdelhi_pressure_hpa": 998.0,
            "usa_wind_kts": 30.0,
            "usa_pressure_hpa": 1000.0,
            "weather_elevation_m": 0.0,
            "temperature_2m_c": 28.4,
            "relative_humidity_pct": 92.0,
            "dew_point_2m_c": 26.5,
            "surface_pressure_hpa": 1002.0,
            "wind_speed_10m_kmh": 40.0,
            "wind_direction_10m_deg": 190.0,
            "wind_gusts_10m_kmh": 55.0,
            "precipitation_1h_mm": 20.0,
            "precipitation_24h_mm": 140.0,
            "precipitation_72h_mm": 280.0,
            "precipitation_168h_mm": 390.0,
            "soil_moisture_0_7cm_m3m3": 0.42,
            "landfall_indicator": 0,
            "distance_to_land_source": 85.0
        }
    }
};
